package-lock.json, package.json, test/controllers/trigger/backlinks.test.js
Related to https://github.com/adobe/spacecat-shared/pull/114
=> fix(deps): update and adjust test for default value for disabled property of audit config

docs/openapi/schemas.yaml, package-lock.json, package.json, src/controllers/sites.js, src/dto/site.js, test/controllers/sites.test.js
=> fix: add update site config to api

package-lock.json, package.json, src/controllers/trigger.js, src/controllers/trigger/organictraffic.js, src/dto/audit.js, test/controllers/trigger/organictraffic.test.js
Add organic traffic audit type
https://jira.corp.adobe.com/browse/SITES-18661
=> feat: add organic traffic audit type (SITES-18661)

src/controllers/hooks.js, test/controllers/hooks.test.js
All site candidate rejections are now logged in a unified way:
1. starts with `Could not process site candidate...`
2. contains the source (ie RUM/CDN)
3. contains the URL of the candidate
```
Could not process site candidate. Reason: .plain.html does not return 2XX, returns 301, Source: CDN, Candidate: https://some-domain.com/index.plain.html
```
to be used to create alert based on this format
=> fix(site-discovery): unified logs

src/support/slack/actions/approve-site-candidate.js, src/support/slack/actions/ignore-site-candidate.js, test/support/slack/actions/approve-friends-family.test.js, test/support/slack/actions/approve-site-candidate.test.js, test/support/slack/actions/ignore-site-candidate.test.js
=> fix(site-discovery): error logs

package-lock.json, package.json
=> fix(deps): bump spacecat-shared-utils to 1.11.5

package-lock.json, package.json, src/controllers/trigger/common/trigger.js, src/dto/organization.js, src/dto/site.js, test/controllers/trigger/apex.test.js, test/controllers/trigger/backlinks.test.js, test/controllers/trigger/common/trigger.test.js, test/controllers/trigger/experiment.test.js, test/controllers/trigger/lhs.test.js, test/controllers/trigger/organictraffic.test.js
=> feat(trigger): organization level audit configs

docs/openapi/schemas.yaml
Ticket: https://jira.corp.adobe.com/browse/SITES-18817
Adding sitemap detection functionality in the audit API spec.
=> chore: add sitemap audit to the API spec

.github/pull_request_template.md, docs/openapi/organization-api.yaml
=> docs: mark endpoints not implemented yet, update PR template

src/index.js, src/utils/route-utils.js, test/utils/route-utils.test.js
=> fix: log error path

src/controllers/hooks.js, test/controllers/hooks.test.js
=> fix(site-discovery): more domains and subdomains filtered

src/controllers/hooks.js, src/support/slack/commands/add-site.js, src/support/utils.js, test/controllers/hooks.test.js, test/support/slack/commands/add-site.test.js
=> feat(add-site): auto detect site type in add site command

package-lock.json, package.json, src/controllers/trigger/cwv.js, src/dto/audit.js, test/controllers/trigger.test.js, test/controllers/trigger/cwv.test.js, test/controllers/trigger/notfound.test.js, test/index.test.js
fixes https://github.com/adobe/spacecat-api-service/issues/222
=> fix(trigger): trigger cwv audit using sites db

src/dto/audit.js
=> fix: use abbr audit only for lhs related audits

src/controllers/hooks.js
=> fix: improved logging for site discovery

src/support/slack/commands.js, src/support/slack/commands/get-exp-candidates.js, src/support/utils.js
Prototype of `get experimentation candidates` command for demo purposes - no test coverage.
=> feat: exp candidates command (WIP)

src/controllers/import.js
=> feat: introduce import APIs

src/controllers/import.js
Avoids "Error: Invalid services: sqsClient is required" issue
=> fix: remove ImportSupervisor call

src/support/utils.js, test/controllers/hooks.test.js, test/support/slack/commands/add-site.test.js
=> fix: simplify is-helix check

src/support/utils.js, test/controllers/hooks.test.js
Improved logging for site detection for debugging
=> fix: improved logging site detection

src/routes/index.js
=> fix: correct controller for the audit patching

src/support/slack/commands/run-audit.js, test/support/slack/commands/run-audit.test.js
=> fix: extend run audit command

src/controllers/hooks.js, src/utils/slack/base.js, test/controllers/hooks.test.js, test/support/slack/actions/slack-fixtures.js
Prevent unfurl for hlx-config related message parts.
=> fix: prevent unfurl for hlx config

package-lock.json, package.json, src/controllers/hooks.js, src/dto/site.js, test/controllers/hooks.test.js
Update the helix config also when a site already has a helix config, but the config changed.
=> fix: update hlx config when changed

src/controllers/hooks.js, test/controllers/hooks.test.js
=> fix: suppress unnecessary slack noise coming from hlx config updates

package-lock.json, package.json, src/support/import-supervisor.js
[SITES-23346](https://jira.corp.adobe.com/browse/SITES-23346)
* Add urlCount to the data access layer.
* Update the version of spacecat-shared-data-access to the latest version. Related PR: https://github.com/adobe/spacecat-shared/pull/287
=> feat: add urlCount to the data access layer

src/support/import-supervisor.js, test/controllers/import.test.js
In `getAvailableImportQueue(..)`, check first to ensure none of the RUNNING import jobs are associated with the current API key. If they are, return a `429 Too Many Requests` response.
https://jira.corp.adobe.com/browse/SITES-23399
=> feat: Enforce a maximum of 1 running import job per API key

package-lock.json, package.json, test/dev/server.mjs
=> chore: fix local development

docs/openapi/tools-api.yaml, package-lock.json, src/controllers/import.js, src/index.js, src/support/import-supervisor.js, test/controllers/import.test.js
[SITES-23633](https://jira.corp.adobe.com/browse/SITES-23633)
API service controller updates to use new auth.checkScopes method, and return 401 when unauthorized
This PR depends on the spacecat-shared PR :https://github.com/adobe/spacecat-shared/pull/323
=> feat: add scopes in the import controller

src/controllers/hooks.js
=> fix(site-detection): ignore domains

src/dto/import-job.js
[SITES-23134](https://jira.corp.adobe.com/browse/SITES-23134)
Related PR: https://github.com/adobe/spacecat-content-scraper/pull/166
=> fix: Change the getter for redirectCount

package-lock.json, package.json
=> fix: update shared utils

src/controllers/hooks.js
=> fix(site-detection): reject all previously evaluated candidates

package-lock.json, package.json
=> fix: package version

src/controllers/audits.js, test/controllers/audits.test.js
=> fix: latest audits api response

src/controllers/sites.js, src/index.js, src/support/slack/commands/add-site.js, test/controllers/sites.test.js, test/support/slack/commands/add-site.test.js
Issue was reported on slack https://cq-dev.slack.com/archives/C05A45JBP9N/p1736239541842339
=> fix: create site

src/controllers/hooks.js
=> fix(site-detection): optional override helix check param

src/controllers/sites.js, test/controllers/sites.test.js
=> fix(sites): update hlxConfig via API

src/support/slack/commands/get-sites.js, test/support/slack/commands/get-sites.test.js
=> feat(slack): get sites by ims org id

package-lock.json, package.json
=> fix(data-access): rollback to 2.8.4

src/support/slack/commands/onboard.js, test/support/slack/commands/onboard.test.js
=> fix: org creation in onboard command

src/support/slack/commands/onboard.js, test/support/slack/commands/onboard.test.js
=> fix: global configuration concurrency issue while saving

src/support/slack/commands/onboard.js
=> fix: wrap site.save() in try-catch block

static/onboard/profiles.json
=> fix: fix end date in profiles config

src/support/slack/commands/run-import.js
introfucing bulk import command
=> feat: introduce bulk import

src/support/slack/commands/onboard.js, test/support/slack/commands/onboard.test.js
=> feat: improve logging, add org and site id to report

src/support/slack/commands/onboard.js, test/support/slack/commands/onboard.test.js
=> fix: improve error handling for site creation failures

src/support/slack/commands/onboard.js, test/support/slack/commands/onboard.test.js
=> fix: use correct organization id when creating site

package-lock.json, package.json, src/controllers/sites.js
=> fix(data-access): introduce fetchAllPages flag to sites all

package-lock.json, package.json
=> fix(data-access): fix fetchAllPages flag to sites all

src/controllers/preflight.js, src/index.js, src/routes/index.js, test/controllers/preflight.test.js, test/routes/index.test.js
introducing new `preflight` endpoint with mocked data for POC.
=> feat: introduce preflight endpoint with mocked data

.nycrc.json, src/controllers/demo.js, src/index.js, src/routes/index.js, test/index.test.js, test/routes/index.test.js
Throw away code to be removed later on.
=> fix: demo preparations

src/index.js, src/mcp/registry.js, src/mcp/registry/resources/scrape-content.js, src/mcp/registry/tools/scrape-content.js, src/utils/jsonrpc.js, test/controllers/mcp.test.js
Expose scraped content via mcp tool
=> feat: add scraper mcp tools support

docs/cursor/add-mcp-tool.prompt, docs/cursor/readme.md
Adds a Custom Mode prompt for Cursor:
This guide explains how to install and use the "MCP Tool/Resource Template Builder" prompt in Cursor. This mode is designed to assist you in creating new Model Context Protocol (MCP) tools or resource templates for your project by guiding you through a structured conversation.
The "MCP Tool/Resource Template Builder" is a specialized system prompt, saved in this repo in a file named `add-mcp-tool.prompt`. When you provide the content of this file to Cursor (as a "Custom Mode"), Cursor's AI will adopt the persona and follow the rules defined in the prompt to help you build MCP components.
Refer to the Cursor Custom Mode documentation on how to add this prompt to your Cursor: https://docs.cursor.com/chat/custom-modes
Once the Custom Mode is setup, …
=> docs: add MCP Cursor Custom Mode

src/mcp/registry/tools/sites.js
Add new import types to MCP server. For Project E
=> feat: new organic keyword imports

src/mcp/registry/tools/sites.js
=> fix: typo issue for keywords

src/support/access-control-util.js, test/index.test.js, test/support/access-control-util.test.js
=> fix: api-key auth flow fix

package-lock.json, package.json
=> fix: case insensitive email check

src/controllers/preflight.js, test/controllers/preflight.test.js
=> fix: adding non auth sites

static/onboard/profiles.json
=> fix: add scrape-top-pages to demo profile

README.md
=> fix: empty commit to force release

src/controllers/sites.js, src/dto/site.js, test/controllers/sites.test.js
=> feat: introduce isSandbox flag for sandbox sites

src/support/slack/commands.js, src/support/slack/commands/run-traffic-analysis-backfill.js, test/support/slack/commands/run-traffic-analysis-backfill.test.js
=> feat(slack): add new command for traffic analysis backfill

README.md
=> docs: update README with additional dev environment variables

package-lock.json, package.json
- [LLMO-198 | Display intent form for agentic/referral trial customers](https://jira.corp.adobe.com/browse/LLMO-198)
- [ELMO UI | feat: add onboarding customer intent form for trial customers](https://github.com/adobe/project-elmo-ui/pull/104)
- [spacecat-api-service | feat: add endpoints for new customerIntent config property](https://github.com/adobe/spacecat-api-service/pull/1117)
- [spacecat-shared | feat: …
=> fix: upgrade dependency version for LLMO config

src/controllers/paid/traffic.js
=> fix: extra logs for the api-gateway requests

src/controllers/paid/traffic.js
=> fix: include api-gateway request id in the logs

src/support/slack/commands/run-import.js
“ahref” -> “ahrefs”
https://jira.corp.adobe.com/browse/LLMO-19
https://jira.corp.adobe.com/browse/LLMO-36
https://jira.corp.adobe.com/browse/LLMO-185
=> fix: naming of the new llmo prompts import

src/support/slack/commands.js, src/support/slack/commands/llmo-onboard.js, test/support/slack/commands/llmo-onboard.test.js
=> feat: llmo onboard for site.

src/support/slack/commands/run-traffic-analysis-backfill.js
=> feat(slack): add source to import logs

docs/openapi/schemas.yaml, src/support/slack/commands/run-audit.js
=> feat: added new audit-type llm-error-pages

static/onboard/profiles.json
=> feat: Update demo profile to include forms opportunities

src/controllers/reports.js, test/controllers/reports.test.js
=> fix: added mystique pre-signed url return for reports

src/controllers/user-activities.js, test/controllers/user-activities.test.js
=> fix: add first name and last name in first login

src/controllers/preflight.js
=> fix: revert lorem ipsum check name for preflight

src/controllers/llmo/llmo-mappings.js
Triggers release of LLMO endpoint for filtering data
[LLMO-424](https://jira.corp.adobe.com/browse/LLMO-424)
=> feat: Triggers release of LLMO endpoint for filtering data - LLMO-424

test/controllers/brands.test.js, test/controllers/preflight.test.js, test/controllers/sandbox-audit.test.js, test/controllers/sites.test.js
[Renovate bot ](https://github.com/adobe/spacecat-api-service/pull/1300)failing after https://github.com/adobe/spacecat-api-service/pull/1303/files. due to missing debug loggerStub .
https://github.com/adobe/spacecat-api-service/pull/1300
=> fix: adds debug log in loggerStub

src/support/slack/commands/onboard.js, src/support/utils.js
=> fix: add log and slack messages to provide visibility on error conditions

src/controllers/entitlements.js, src/routes/index.js, test/controllers/entitlements.test.js, test/routes/index.test.js
=> feat: create entitlement API
