src/dto/audit.js, test/dto/audit.test.js
APIs such as Retrieve all latest audits of a given type were not returning the content of the broken backlinks audit result, as it has a different format than the one existing (with scores, runtime error etc.).
=> fix: API should return audit result for broken backlinks also in abbreviated JSON

src/controllers/trigger/backlinks.js
now that broken-backlinks fully moved to post processor, initial message for the internal report is being sent there. We should not sent the initial message in api-service anymore
=> feat(trigger): no initial msg for backlink audit

docs/openapi/event-api.yaml, src/support/auth.js, test/support/auth.test.js
Ticket: SITES-20314 - Configure /event/fulfillment endpoint as one of the ADMIN_ENDPOINTS
Prevent user level access to the Fulfillment Handler endpoint.
=> fix: configure /event/fulfillment as one of the ADMIN_ENDPOINTS

docs/openapi/api.yaml, docs/openapi/schemas.yaml, docs/openapi/slack-api.yaml
Spec update for #207 
Update the API spec to replace `email` based invitation mechanism with one based upon IMS user ID, as read from the IMS user token.
=> feat: Endpoint to request an invite to an organization's Slack channel by user ID - API spec update

src/support/slack/commands/get-sites.js, test/support/slack/commands/get-sites.test.js
Sites from the Friends and Family organization are no longer audited and are not relevant for customer queries. Therefore, we will exclude them from the "get all sites" command list using a filter.
=> feat: filter friends and family organization from get all sites command

docs/openapi/schemas.yaml
api spec proposal for https://github.com/adobe/spacecat-api-service/issues/230
1. introduces `goLiveDate` instead of `liveToggledAt` in `site` model
2. depracates `isLive` flag  in site model
3. uses `deliveryType` enum instead of `isLive` flag in `audit` model
=> feat(api-spec): the new edge go live date field

.circleci/config.yml, docs/openapi/api.yaml, docs/openapi/schemas.yaml
Upgrades openapi to version 3.1.0
Fixes multiple examples use
Add docs linting to PR checks
Fixes: https://github.com/adobe/spacecat-api-service/issues/263
=> fix: docs linting, openapi version upgrade and multiple examples support

src/controllers/slack.js
#256 - Use of .id instead of .getId() results in undefined in logs
=> fix: Use of .id instead of .getId() results in undefined in logs #256

src/support/slack/commands/get-exp-candidates.js, src/support/utils.js
Adjust to the new message format expected by the content scraper.
=> fix: message format for exp candidates

src/support/import-supervisor.js, test/controllers/import.test.js
Formerly we used the `import/` directory in S3. This PR updates the code to use `imports/`.
=> fix: use correct 'imports/' prefix when creating a presigned URL to import-result.zip

src/index.js, test/index.test.js
Allow `authorization` header. This is required for IMS authentication.
=> fix: allow authorization header

src/controllers/hooks.js, test/controllers/hooks.test.js
As the `domain` coming via the `x-fwd-host` may change with ports and no ports (e.g. `domain:443` vs `domain`) and other reasons, as well as because the `domain` is not part of the hlx config per se, this should be removed from the config as we store it. this will significantly reduce updates to the config. At the same time, standardize the stored `cdn` config to match the original.
=> fix: hlx config updates too much

src/index.js, test/index.test.js
Enables browser preflight, which currently is blocked: "Request header field x-import-api-key is not allowed by Access-Control-Allow-Headers in preflight response."
=> fix: Include x-import-api-key header in Access-Control-Allow-Headers

src/controllers/import.js, test/controllers/import.test.js
Add a new property to the `IMPORT_CONFIGURATION` env to support limiting imports to a maximum number of URLs per job.
- https://jira.corp.adobe.com/browse/SITES-23365
=> feat: Enforce a maximum number of URLs that can be imported per job

.circleci/config.yml, .husky/pre-commit, package-lock.json, src/support/auth/handlers/ims.js, test/support/auth/handlers/ims.test.js
Support for Node 20.15.1 by fixing IMS tests. Issue is that `nock` no longer intercepts requests made by the `jose` library when using a remote key set. I have adjusted the implementation to support local key sets for testing.
=> fix: update node 20.15.1

package-lock.json, package.json, src/support/import-supervisor.js, test/controllers/import.test.js
[SITES-23948](https://jira.corp.adobe.com/browse/SITES-23948)
Update spacecat-service to send hashedApiKey instead of apiKey while creating a new import job
PR: https://github.com/adobe/spacecat-shared/pull/318/files needs to be merged in before I modify the unit tests for this one.
=> feat: Update spacecat-service to send hashedApiKey during createImportJob

package-lock.json, package.json, src/controllers/import.js, src/dto/import-job.js, src/index.js, src/routes/index.js, src/support/import-supervisor.js, test/controllers/import.test.js, test/routes/index.test.js
[SITES-23126](https://jira.corp.adobe.com/browse/SITES-23126)
Build out the API to get all the import jobs data for representation in PowerBI
- getAllImportJobs - To retrieve all the import jobs started between a specified startDate and endDate
Sample response:
```
[{
"id": "50ad5e05-bc98-4810-a264-e1043bf7847b",
"baseURL": "https://www.testing.ca",
"options": {
"enableJavascript": false,
"scrollToBottom": true
},
"startTime": "2024-08-21T16:38:05.446Z",
"status": "RUNNING",
"urlCount": 1,
"importQueueId": "spacecat-import-queue-1-dev",
"initiatedBy": {
"apiKeyName": "Dev Key",
"userAgent": "insomnia/2023.5.8-adobe",
"imsUserId": "Ottawa-team",
"imsOrgId": "Adobe"
}
}]
```
=> feat: API to get all import jobs

src/controllers/hooks.js, test/controllers/hooks.test.js
Add ability to configure ignored domains and sub-domain tokens via configuration:
=> fix: make ignored (sub-/domains) configurable

package-lock.json, package.json, src/controllers/import.js, test/controllers/import.test.js
[SITES-22756](https://jira.corp.adobe.com/browse/SITES-22756)
An API key owner has to specifically allowlist domains before they can be processed by Import as a Service.
We do not want to allow imports on domains which are not part of the allowlist for a given user.
=> feat: Restrict importing URLs which are not allowlisted (by domain) for the API key

src/controllers/assistant.js, test/controllers/assistant.test.js
When making the call to Firefall, we use the IMS Org Id associated with the Importer API KEY.  If it is not present, or was not processed correctly by the `ScopedApiKeyHandler`, the Assistant Service will return a 401 (UNAUTHORIZED).
For now, we also allow it to be specified in the 'x-gw-ims-org-id' header, although that may be removed in Phase 2.
https://jira.corp.adobe.com/browse/SITES-26996
=> fix: SITES-26996 [Import Assistant] Context ImsOrg not being used by Firefall Client

.github/workflows/e2e-tests.yaml
Fixes the E2E tests which have been failing, for example: https://github.com/adobe/spacecat-api-service/actions/runs/12583579509/job/35071446280
Error message:
```
npm error code EBADENGINE
npm error engine Unsupported engine
npm error engine Not compatible with your version of node/npm: @adobe/spacecat-shared-data-access@1.[6](https://github.com/adobe/spacecat-api-service/actions/runs/12583579509/job/35071446280#step:4:7)1.12
npm error notsup Not compatible with your version of node/npm: @adobe/spacecat-shared-data-access@1.61.12
npm error notsup Required: {"node":">=22.0.0 <23.0.0","npm":">=10.9.0 <12.0.0"}
npm error notsup Actual:   {"npm":"10.[8](https://github.com/adobe/spacecat-api-service/actions/runs/12583579509/job/35071446280#step:4:9).1","node":"v20.16.0"}
```
=> fix: Bump node version used by importer E2E test workflow

src/support/import-supervisor.js, test/controllers/import.test.js
Post V2 data access update, we are unable to poll for job status using the `/tools/import/jobs/{{jobId}}/progress` endpoint.
=> fix: Import job progress endpoint

test/e2e/fixtures/jobs.js, test/e2e/import.e2e.js, test/e2e/utils/request-helpers.js
The Import as a Service E2E tests are failing, which appears to be due to our attempts to import pages which are already running on Edge Delivery services. This PR updates the URLs we are testing with to use URLs that are still within our control (personal blog) but are not currently running on Edge. This change has enabled our E2Es to again import reliably, avoid the errors we see (consistently) with the b.a.com `site-performance.html` URL:
```
[jobId=e2f949a4-2a36-49f7-bfc2-9f142b77da35] Cannot download image https://business.adobe.com/products/experience-manager/sites/media_16ffa3bed3a56c65bfb15255dcdd6d5bb5eb3d1ce.png?width=750&format=png&optimize=medium: Stream closed with error code NGHTTP2_INTERNAL_ERROR
...
[jobId=e2f949a4-2a36-49f7-bfc2-9f142b77da35] [import] Failed to scrape …
```
=> fix: Update URLs used for Import as a Service E2E tests

src/support/slack/commands/run-import.js, src/support/slack/commands/run-scrape.js, test/support/slack/commands/run-scrape.test.js
Until BO office has convenient configuration setting (slack roles), disable role check to facilitate easy Summit/GA site onboarding.
=> fix: temporarily disable role check

src/support/slack/commands/run-import.js
Make sure the confirming slack message does not contain "undefined-undefined" when no start and end dates are given for an iport command.
=> fix: range may be undefined

.github/workflows/e2e-tests.yaml
We have an error running our E2E test workflow that started this morning (https://github.com/adobe/spacecat-api-service/actions/runs/13523022713/job/37796886455). I cannot reproduce it locally: 
```
npm warn deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
npm warn deprecated eslint@8.57.1: This version is no longer supported. Please see https://eslint.org/version-support for other options.
npm error code E401
npm error Incorrect or missing password.
npm error If you were trying to login, change your password, create an
npm error authentication token or enable two-factor authentication then
npm error that means you likely typed your password in incorrectly.
npm error Please try again, or recover your password at:
npm error   https://www.npmjs.com/forgot
``` …
=> fix: Update Importer E2E test workflow to use the existing Setup Node & NPM action

src/support/slack/commands/run-audit.js, test/support/slack/commands/run-audit.test.js
fix `run audit all` executing only lhs audits
=> fix: all audit command triggers only lhs

src/support/slack/commands/onboard.js
Onboarding an existing site with a new IMS org did not update the site org.
=> fix: onboarding for existing site

src/support/slack/commands.js, src/support/slack/commands/toggle-site-import.js, test/support/slack/commands/toggle-site-import.test.js
- Added Enable/Disable feature for imports for single url and CSV for single import type or profile based
=> feat: toggle-site-imports Slack command for enabling/disabling imports

src/support/sqs.js, test/support/sqs.test.js
We run with a mixture of SQS queue names and urls in all environment.
Since we have been passing queue URLs through to the AWS SDK as is, raw queue names lead to errors rather than successful queue operations.
The changes introduced here first check whether the provided queue url _or name_ can be parsed as URL, and if not, tries to retrieve the url for the named queue.
https://jira.corp.adobe.com/browse/SITES-30735
=> fix: Support SQS Queue Names

src/index.js, test/index.test.js
Allows `x-client-type` header. This is required to distinguish between API clients. 
JIRA: https://jira.corp.adobe.com/browse/SITES-30942
=> feat: adding client type header

src/controllers/mcp.js, src/routes/index.js, test/routes/index.test.js
Issue:
When connecting to MCP server we can see errors in logs
`[73003] Error from remote server: StreamableHTTPError: Streamable HTTP error: Failed to open SSE stream: Not Found`
Fix is to not allow this method for sse connection as described in docs:
https://modelcontextprotocol.io/specification/2025-03-26/basic/transports#listening-for-messages-from-the-server
=> fix: sse related errors by not allowing get method

src/mcp/registry/tools/sites.js
update description for getSiteByBaseURLTool
Issue: we encoding url inside fetchfn and description asking for encoded url causing issues.
Fix is to improve description to ask clearly the plain url
=> fix: update description for getSiteByBaseURLTool

src/mcp/registry/resources/audits.js, src/mcp/registry/tools/audits.js, test/controllers/mcp.test.js
- some mcp clients may need to analyze how a change has effected CWV; so we need to return all audits to build an analysis of the effect of a change overtime!
=> feat: add mcp endpoint to return all audits for historical analysis

src/support/slack/commands/run-scrape.js, src/support/utils.js, test/support/slack/commands/run-scrape.test.js
For certain domains, we've seen the default concurrency used in the scraper not sufficient and lambda is timing out. In those cases, running the spacecat command with lower batchSize and allowCache will allow the scrape to be completed with one command, then since the audit uses the allowCache, scrape triggered from the audit will complete fast (as the urls are already scraped using slack command) and audits will proceed.
Relates to https://github.com/adobe/spacecat-content-scraper/pull/404
Fixes https://jira.corp.adobe.com/browse/SITES-32535
Example run
```
@spacecat run scrape [test.com](http://test.com/) 5 true
```
=> fix: add support for batchSize and allowCache options to scrape slack command

src/support/slack/commands/add-repo.js, src/support/slack/commands/add-site.js, src/support/slack/commands/onboard.js, src/support/slack/commands/run-audit.js, src/support/utils.js, test/support/slack/commands/add-repo.test.js, test/support/slack/commands/add-site.test.js, test/support/slack/commands/run-audit.test.js
Adds an optional extra arg to our Slack bot that allows to pass a string
argument when running an audit.
Useful e.g. to pass a date for backfilling
https://jira.corp.adobe.com/browse/LLMO-19
https://jira.corp.adobe.com/browse/LLMO-36
https://jira.corp.adobe.com/browse/LLMO-185
=> feat: slack 'run audit' command supports extra arg 

src/support/slack/commands/llmo-onboard.js, test/support/slack/commands/llmo-onboard.test.js
Enable agentic traffic audits on onboard-llmo
`cdn-analysis` is per bucket/org, we need to enable only once per org.
=> feat: enable agentic traffic audits on onboard

src/support/slack/actions/onboard-llmo-modal.js
Remove delivery type required (since if it's already onboarded to spacecat, the value can be left away)
=> Llmo onboarding hotfix

src/controllers/paid/traffic.js, test/controllers/paid/traffic.test.js
its more common that empty result is result of missing import, caching this results in cleanup work 
so lets not cache it
=> fix: dont cache empty result

package-lock.json, package.json, src/controllers/slack.js, src/support/slack/actions/index.js, src/support/slack/actions/onboard-llmo-modal.js, src/support/slack/commands/llmo-onboard.js, test/support/access-control-util.test.js, test/support/slack/actions/onboard-llmo-modal.test.js, test/support/slack/commands/llmo-onboard.test.js
- reuses the same command for onboarding
- if brand exists for given site, the users will be prompted with two buttons:
- users can choose to only add/update entitlements and enrollments (this is done using the tier client)
- they can also choose to update the IMS org, and subsequently update the entitlements and enrollments
- success and failure messages are posted in the same thread
=> fix(slack/onboarding-llmo): allow rerun of onboarding command
